pipeline {
    agent any
    environment {        
        String SCRIPTS_FOLDER = pwd()
        String ENV_FOLDER = "C:\\Jenkins\\jobs_env_vars\\outorgas"
        String PY_REL_PATH = "venv\\Scripts\\python.exe"
        String PYTEST_REL_PATH = "venv\\Scripts\\pytest.exe"
        APP_FOLDER = null
        ENV_FILE = null
        python = null
        pytest = null
    }    

    stages {
        stage('#### Preparation ####') {
             steps {                                
                echo "${env.scriptsFolder}"
                script {                                   
                    ENV_FILE = readFile("${ENV_FOLDER}\\.env") //Utilizado pela função groovyScripts.getDotEnvValue()
                    
                    def groovyFilePath = env.BRANCH_NAME ? "${SCRIPTS_FOLDER}\\CI\\scripts.groovy" : "C:\\Users\\m1107819\\Coding\\outorgas\\CI\\scripts.groovy"                    
                    groovyScripts = load groovyFilePath                    
                    APP_FOLDER =  groovyScripts.getDotEnvValue('APP_FOLDER')                        
                    
                    python = "${APP_FOLDER}\\${PY_REL_PATH}"                    
                    pytest = "${APP_FOLDER}\\${PYTEST_REL_PATH}"
                    
                    println "*** App folder is ---> ${APP_FOLDER}"
                    println "*** Current branch is ---> ${env.BRANCH_NAME}"
                }                
            }
        }
        stage('#### Build ####') {
            when{
               expression {
                    true | env.BRANCH_NAME == 'main'
                }
            }
            steps {
                echo 'Build step -> installing dependencies listed in requirements.txt...'
                bat """
                cd ${APP_FOLDER}\\venv\\Scripts 
                activate && pip install -r ..\\..\\requirements.txt
                """
            }            
        }        
        stage('#### Test ####') {
            when{
               expression {
                    env.BRANCH_NAME == 'main'
                }
            }
            steps {                
                bat """
                ${python} --version
                cd ${APP_FOLDER}\\venv\\Scripts 
                activate && cd ..\\.. && ${pytest} ./src/tests/unit/
                """                                
            }
        } 
        stage('#### Deploy ####') {
            when{
               expression {
                    env.BRANCH_NAME == 'main'
                }
            }
            steps {
                bat """
                cd ${APP_FOLDER}\\venv\\Scripts 
                activate && cd ..\\.. && cd && git pull
                """                               
                bat "pm2 status"
            }
        }   
    }
    
     post{
        success {
            echo '++++++++ Alright, pipeline runned sucessfully.'            
        }
        failure {
            echo '-------- Somehting went wrong running Jenkins jobs...'            
        }
    }
}